"""Иконка в категорию

Revision ID: 386f9c096f8f
Revises: 95a74d9b51d3
Create Date: 2025-04-14 00:41:31.604434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386f9c096f8f'
down_revision: Union[str, None] = '95a74d9b51d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('icon', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'themes', 'levels', ['level'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('category', 'icon')
    # ### end Alembic commands ###
