"""Themes migration

Revision ID: 544a5f594a1a
Revises: 0a28fa6b5334
Create Date: 2025-04-06 19:21:18.316469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544a5f594a1a'
down_revision: Union[str, None] = '0a28fa6b5334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'themes', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_column('themes', 'category')
    # ### end Alembic commands ###
